import { PrivacyGuardTestCase } from "./preCommitScannerTestCases";

export const configurationFailureTestCases: PrivacyGuardTestCase[] = [
  {
    id: "TC-41",
    title: "Wrong provider key",
    area: "Configuration - Error and Failure Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Set provider to openai but only fill anthropicApiKey.",
    expectedResult: "Error shown: 'No API key set for provider openai. Configure privacyGuard.openaiApiKey'.",
    tags: ["configuration", "provider", "missing-key", "error-handling"],
  },
  {
    id: "TC-42",
    title: "All keys empty",
    area: "Configuration - Error and Failure Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Leave all three API key fields blank, then run any scan.",
    expectedResult: "Error names exactly which key is missing for the selected provider.",
    tags: ["configuration", "missing-key", "error-handling"],
  },
  {
    id: "TC-43",
    title: "Invalid API key",
    area: "Configuration - Error and Failure Cases",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Set a malformed or expired API key, then run a scan.",
    expectedResult: "API returns 401; error is caught and shown in panel; commit is not blocked.",
    tags: ["configuration", "invalid-key", "api-error", "allows-commit"],
  },
  {
    id: "TC-44",
    title: "Wrong OpenRouter model slug",
    area: "Configuration - Error and Failure Cases",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Set openRouterModel to not-a-real-model, then run a scan.",
    expectedResult: "OpenRouter returns model-not-found error; error is caught in panel; commit proceeds.",
    tags: ["configuration", "openrouter", "model-error", "allows-commit"],
  },
  {
    id: "TC-45",
    title: "No internet connection",
    area: "Configuration - Error and Failure Cases",
    priority: "critical",
    automationLevel: "manual",
    setup: "Disconnect from the internet, then make a commit.",
    expectedResult: "Hook prints warning and exits 0; commit proceeds; hook never blocks on tool or network failure.",
    tags: ["configuration", "network", "hook", "allows-commit", "critical"],
  },
  {
    id: "TC-46",
    title: "API timeout or slow response",
    area: "Configuration - Error and Failure Cases",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Simulate a slow network, then make a commit.",
    expectedResult: "Request eventually fails; failure is caught; commit proceeds with a warning.",
    tags: ["configuration", "timeout", "hook", "allows-commit"],
  },
  {
    id: "TC-47",
    title: "Malformed AI response",
    area: "Configuration - Error and Failure Cases",
    priority: "critical",
    automationLevel: "automated",
    setup: "Make the AI return non-JSON output, such as from a prompt-injection scenario.",
    expectedResult: "JSON parse failure is caught; commit proceeds; extension does not crash or leak data.",
    tags: ["configuration", "malformed-response", "json", "allows-commit"],
  },
];
