import { PrivacyGuardTestCase } from "./preCommitScannerTestCases";

export const dependencyScannerTestCases: PrivacyGuardTestCase[] = [
  {
    id: "TC-15",
    title: "Known tracking packages",
    area: "Dependency Scanner - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Use package.json dependencies containing google-analytics, mixpanel, and amplitude.",
    expectedResult: "All three packages are scored HIGH_RISK; alternatives are suggested for each.",
    tags: ["dependencies", "analytics", "high-risk"],
  },
  {
    id: "TC-16",
    title: "Safe dev tools only",
    area: "Dependency Scanner - Happy Path",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Use package.json dependencies containing typescript, eslint, jest, and prettier.",
    expectedResult: "All packages are scored SAFE; no alternatives are needed.",
    tags: ["dependencies", "dev-tools", "safe"],
  },
  {
    id: "TC-17",
    title: "Firebase dependency",
    area: "Dependency Scanner - Happy Path",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Use package.json with firebase as a dependency.",
    expectedResult: "Firebase is scored CAUTION; data-leaves-your-infrastructure and GDPR implications are noted.",
    tags: ["dependencies", "firebase", "caution", "gdpr"],
  },
  {
    id: "TC-18",
    title: "Mixed risk packages",
    area: "Dependency Scanner - Happy Path",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Use package.json dependencies containing axios, lodash, mixpanel, and jest.",
    expectedResult: "Results are grouped into HIGH_RISK, CAUTION, and SAFE sections.",
    tags: ["dependencies", "mixed-risk", "grouping"],
  },
  {
    id: "TC-19",
    title: "Privacy-respecting analytics",
    area: "Dependency Scanner - Happy Path",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Use package.json with @plausible/tracker as a dependency.",
    expectedResult: "@plausible/tracker is scored SAFE and recognized as a privacy-preserving alternative.",
    tags: ["dependencies", "analytics", "privacy-preserving"],
  },
  {
    id: "TC-20",
    title: "Empty dependencies",
    area: "Dependency Scanner - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Use a package.json that has no dependencies or devDependencies fields.",
    expectedResult: "Error shown: 'No dependencies found in package.json'.",
    tags: ["dependencies", "empty-state", "error-handling"],
  },
  {
    id: "TC-21",
    title: "No package.json",
    area: "Dependency Scanner - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Open a Python or Go project with no package.json in the workspace root.",
    expectedResult: "Error shown: 'No package.json found in workspace root'.",
    tags: ["dependencies", "missing-file", "error-handling"],
  },
  {
    id: "TC-22",
    title: "50+ dependencies",
    area: "Dependency Scanner - Edge Cases",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Use a package.json with more than 50 dependencies.",
    expectedResult: "All packages are scored; model token capacity is exercised; no timeout crash occurs.",
    tags: ["dependencies", "large-input", "timeout"],
  },
  {
    id: "TC-23",
    title: "Scoped private package",
    area: "Dependency Scanner - Edge Cases",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Use package.json with @mycompany/internal-sdk as a dependency.",
    expectedResult: "Package is scored CAUTION or SAFE with a low-confidence note; scanner does not crash on unknown package.",
    tags: ["dependencies", "scoped-package", "unknown-package"],
  },
  {
    id: "TC-24",
    title: "No workspace open",
    area: "Dependency Scanner - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Run dependency scanning from the command palette with no folder open in VS Code.",
    expectedResult: "Error shown: 'No workspace open'.",
    tags: ["dependencies", "workspace", "error-handling"],
  },
];
