import { PrivacyGuardTestCase } from "./preCommitScannerTestCases";

export const gitHookTestCases: PrivacyGuardTestCase[] = [
  {
    id: "TC-25",
    title: "First-time activation",
    area: "Git Hook - Installation",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Install the extension and open a project in VS Code for the first time.",
    expectedResult: "Hook is auto-installed; toast says pre-commit hook installed and commits will be scanned automatically.",
    tags: ["hook", "activation", "install"],
  },
  {
    id: "TC-26",
    title: "Verify hook content",
    area: "Git Hook - Installation",
    priority: "high",
    automationLevel: "automated",
    setup: "After activation, inspect .git/hooks/pre-commit.",
    expectedResult: "File contains the '# Privacy Guard pre-commit hook' header.",
    tags: ["hook", "content", "install"],
  },
  {
    id: "TC-27",
    title: "Hook is executable",
    area: "Git Hook - Installation",
    priority: "high",
    automationLevel: "automated",
    setup: "After activation, inspect permissions on .git/hooks/pre-commit.",
    expectedResult: "File has executable permissions equivalent to -rwxr-xr-x.",
    tags: ["hook", "permissions", "install"],
  },
  {
    id: "TC-28",
    title: "Re-open project",
    area: "Git Hook - Installation",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Close and re-open the same project in VS Code.",
    expectedResult: "Hook install is skipped silently; no duplicate toast is shown; behavior is idempotent.",
    tags: ["hook", "activation", "idempotent"],
  },
  {
    id: "TC-29",
    title: "Manual install command",
    area: "Git Hook - Installation",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Run Privacy Guard: Install Pre-Commit Hook from the command palette.",
    expectedResult: "Success message is shown if the hook was not already installed.",
    tags: ["hook", "command", "install"],
  },
  {
    id: "TC-30",
    title: "Existing husky hook",
    area: "Git Hook - Edge Cases",
    priority: "critical",
    automationLevel: "automated",
    setup: "Use a project that already has a pre-commit hook from Husky or another tool.",
    expectedResult: "Warning says a pre-commit hook already exists; existing hook is not overwritten.",
    tags: ["hook", "husky", "do-not-overwrite", "critical"],
  },
  {
    id: "TC-31",
    title: "No .git/hooks directory",
    area: "Git Hook - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Delete the .git/hooks directory, then run the install command.",
    expectedResult: "Directory is created automatically before writing the hook.",
    tags: ["hook", "missing-directory", "install"],
  },
  {
    id: "TC-32",
    title: "Not a git repo",
    area: "Git Hook - Edge Cases",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Open a plain folder with no .git directory.",
    expectedResult: "Hook installation is skipped silently; no error is surfaced to the user.",
    tags: ["hook", "workspace", "error-handling"],
  },
  {
    id: "TC-33",
    title: "Manually deleted hook",
    area: "Git Hook - Edge Cases",
    priority: "medium",
    automationLevel: "manual",
    setup: "Delete .git/hooks/pre-commit manually, then make a commit.",
    expectedResult: "Hook is gone; commit goes through unscanned; extension does not crash.",
    tags: ["hook", "manual-delete", "commit"],
  },
  {
    id: "TC-34",
    title: "Uninstall hook",
    area: "Git Hook - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Run Privacy Guard: Uninstall Pre-Commit Hook.",
    expectedResult: "Hook file is deleted; success message is shown.",
    tags: ["hook", "command", "uninstall"],
  },
  {
    id: "TC-35",
    title: "Reinstall after uninstall",
    area: "Git Hook - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Uninstall the hook, then run Privacy Guard: Install Pre-Commit Hook.",
    expectedResult: "Hook is reinstalled successfully.",
    tags: ["hook", "reinstall", "uninstall"],
  },
];
