export type TestCasePriority = "critical" | "high" | "medium";
export type AutomationLevel = "automated" | "manual" | "manual-or-automated";

export interface PrivacyGuardTestCase {
  id: string;
  title: string;
  area: string;
  priority: TestCasePriority;
  automationLevel: AutomationLevel;
  setup: string;
  expectedResult: string;
  fixture?: string;
  tags: string[];
}

export const preCommitScannerTestCases: PrivacyGuardTestCase[] = [
  {
    id: "TC-01",
    title: "PII in log statement",
    area: "Pre-Commit Check - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Stage a JavaScript file containing a log statement for user.email.",
    fixture: "console.log(user.email)",
    expectedResult: "HIGH risk; commit is blocked; GDPR Article 5 is cited in output.",
    tags: ["diff", "pii", "logging", "gdpr", "blocks-commit"],
  },
  {
    id: "TC-02",
    title: "Safe log statement",
    area: "Pre-Commit Check - Happy Path",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Stage a file with a non-sensitive operational log statement.",
    fixture: "console.log('Server started on port 3000')",
    expectedResult: "LOW risk; no issues are reported; commit proceeds normally.",
    tags: ["diff", "safe-log", "allows-commit"],
  },
  {
    id: "TC-03",
    title: "Third-party data sharing",
    area: "Pre-Commit Check - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Stage a file that sends userData to an analytics endpoint.",
    fixture: "fetch('https://analytics.google.com', { body: JSON.stringify(userData) })",
    expectedResult: "HIGH risk; third-party data sharing is flagged; commit is blocked.",
    tags: ["diff", "third-party", "analytics", "blocks-commit"],
  },
  {
    id: "TC-04",
    title: "Password stored unhashed",
    area: "Pre-Commit Check - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Stage a file that stores req.body.password directly.",
    fixture: "db.users.insert({ password: req.body.password })",
    expectedResult: "HIGH risk; sensitive data storage is flagged; a concrete fix is suggested.",
    tags: ["diff", "password", "storage", "blocks-commit"],
  },
  {
    id: "TC-05",
    title: "Cosmetic-only change",
    area: "Pre-Commit Check - Happy Path",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Stage a CSS or README-only change with no application logic.",
    expectedResult: "LOW risk; zero issues found; commit proceeds; safe-to-commit message is shown.",
    tags: ["diff", "cosmetic", "allows-commit"],
  },
  {
    id: "TC-06",
    title: "Missing consent check",
    area: "Pre-Commit Check - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Stage code that collects location through navigator.geolocation without a consent gate.",
    fixture: "navigator.geolocation.getCurrentPosition(sendLocation)",
    expectedResult: "MEDIUM or HIGH risk; missing consent check is flagged; GDPR Article 7 is cited.",
    tags: ["diff", "location", "consent", "gdpr"],
  },
  {
    id: "TC-07",
    title: "Token in environment",
    area: "Pre-Commit Check - Happy Path",
    priority: "critical",
    automationLevel: "manual-or-automated",
    setup: "Stage source containing a hardcoded token.",
    fixture: "const token = 'sk-abc123'",
    expectedResult: "HIGH risk; hardcoded secret is flagged.",
    tags: ["diff", "secret", "token", "blocks-commit"],
  },
  {
    id: "TC-08",
    title: "Nothing staged",
    area: "Pre-Commit Check - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Run Privacy Guard: Check Staged Changes with no staged files and no unstaged diff.",
    expectedResult: "Error shown: 'No changes found. Stage your changes with git add first.'",
    tags: ["diff", "empty-state", "error-handling"],
  },
  {
    id: "TC-09",
    title: "Large diff over 8000 characters",
    area: "Pre-Commit Check - Edge Cases",
    priority: "high",
    automationLevel: "automated",
    setup: "Stage a file with more than 500 lines of code changes.",
    expectedResult: "Diff is truncated to 8000 characters, '...(truncated)' is appended, and analysis completes.",
    tags: ["diff", "large-input", "truncation"],
  },
  {
    id: "TC-10",
    title: "Variable named like PII",
    area: "Pre-Commit Check - Edge Cases",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Stage code where userEmail is only a local calculation result and is not logged, stored, or transmitted.",
    fixture: "const userEmail = calculateScore()",
    expectedResult: "LOW risk; variable names alone are not over-flagged without actual data exposure.",
    tags: ["diff", "false-positive", "pii"],
  },
  {
    id: "TC-11",
    title: "Binary file staged",
    area: "Pre-Commit Check - Edge Cases",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Stage an image or compiled JavaScript bundle.",
    expectedResult: "Unreadable diff is handled gracefully; extension does not crash.",
    tags: ["diff", "binary", "error-handling"],
  },
  {
    id: "TC-12",
    title: "Multi-file commit",
    area: "Pre-Commit Check - Edge Cases",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Stage changes across five different files simultaneously.",
    expectedResult: "All files are analyzed in one diff; each issue reports the correct filename.",
    tags: ["diff", "multi-file", "reporting"],
  },
  {
    id: "TC-13",
    title: "git commit --no-verify",
    area: "Pre-Commit Check - Edge Cases",
    priority: "medium",
    automationLevel: "manual",
    setup: "Run git commit --no-verify on a file containing console.log(user.email).",
    fixture: "console.log(user.email)",
    expectedResult: "Hook is bypassed entirely; commit succeeds; this is expected Git behavior.",
    tags: ["git", "hook", "bypass"],
  },
  {
    id: "TC-14",
    title: "Not a git repo",
    area: "Pre-Commit Check - Edge Cases",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Open a plain folder with no .git directory and run the check from the sidebar.",
    expectedResult: "Error is caught and displayed in the panel; extension does not crash.",
    tags: ["git", "error-handling", "workspace"],
  },
];
