import { PrivacyGuardTestCase } from "./preCommitScannerTestCases";

export const providerConfigurationTestCases: PrivacyGuardTestCase[] = [
  {
    id: "TC-36",
    title: "Anthropic provider",
    area: "Provider Configuration",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Set provider to anthropic, fill anthropicApiKey, and run a check.",
    expectedResult: "Scan runs; terminal output shows '[anthropic]'.",
    tags: ["provider", "anthropic", "configuration"],
  },
  {
    id: "TC-37",
    title: "OpenAI provider",
    area: "Provider Configuration",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Set provider to openai, fill openaiApiKey, and run a check.",
    expectedResult: "Scan runs; terminal output shows '[openai]'.",
    tags: ["provider", "openai", "configuration"],
  },
  {
    id: "TC-38",
    title: "OpenRouter provider",
    area: "Provider Configuration",
    priority: "high",
    automationLevel: "manual-or-automated",
    setup: "Set provider to openrouter, fill openrouterApiKey, set a model slug, and run a check.",
    expectedResult: "Scan runs; terminal output shows '[openrouter]'.",
    tags: ["provider", "openrouter", "configuration"],
  },
  {
    id: "TC-39",
    title: "Switch provider without re-entering keys",
    area: "Provider Configuration",
    priority: "medium",
    automationLevel: "manual-or-automated",
    setup: "Fill all three provider key fields, then switch provider from openrouter to openai.",
    expectedResult: "Correct key is selected automatically; user is not prompted to re-enter a key.",
    tags: ["provider", "settings", "key-selection"],
  },
  {
    id: "TC-40",
    title: "Custom OpenRouter model",
    area: "Provider Configuration",
    priority: "medium",
    automationLevel: "manual",
    setup: "Set provider to openrouter and openRouterModel to deepseek/deepseek-r1-0528.",
    expectedResult: "That specific model is used, verified by checking response style.",
    tags: ["provider", "openrouter", "model-selection"],
  },
];
